version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ADDR: 0.0.0.0:8080

  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_URI: mongodb://db:27017
    ports:
      - "27017:27017"
