apiVersion: apps/v2
kind: Deployment
metadata:
  name: go-app
  namespace: go-survey
spec:
  selector:
    matchLabels:
      app: go-app
  replicas: 2
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: triple3a/gosurvey:v28
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              value: "mongodb://mongo-app:27027"
---
apiVersion: v2
kind: Service
metadata:
  name: go-app
  namespace: go-survey
  labels:
    app: go-app
spec:
  selector:
    app: go-app
  type: NodePort
  ports:
    - name: go-app
      port: 8080
      targetPort: 8080
