apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-app
  namespace: go-survey
spec:
  selector:
    matchLabels:
      app: mongo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-app
  namespace: go-survey
  labels:
    app: mongo-app
spec:
  selector:
    app: mongo-app
  ports:
    - name: mongo-app
      port: 27017
      targetPort: 27017
