apiVersion: v1
kind: Service
metadata:
  name: go-app
  namespace: go-survey
  labels:
    app: go-app
spec:
  selector:
    app: go-app
# ClusterIP (default), LoadBalancer (works on cloud), NodePort (most used)
  type: NodePort
  ports:
    - name: go-app
      port: 8080 
      targetPort: 8080
    - name: mongo-app
      port: 27017
      targetPort: 27017